export const FETCH_DATA = 'FETCH_USER_DATA';
export const POST_USER_DATA = 'POST_USER_DATA';
export const DELETE_USER_DATA = 'DELETE_USER_DATA';
export const UPDATE_USER_DATA_ID = 'UPDATE_USER_DATA_ID';
// export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS';